name: Generate and Upload Zip Files

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Python environment
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # Install any necessary Python dependencies (e.g., if you use any non-standard libraries)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    # Run your Python script to generate the zip files
    - name: Run zip generation script
      run: |
        cd scripts
        python zipall.py

    # Get the release upload URL
    - name: Get release upload URL
      id: get_release
      run: |
        release_info=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/repos/PrefLib/PrefLib-Data/releases/tags/v1.0)

        echo "upload_url=$(echo $release_info | jq -r .upload_url | sed -e 's/{?name,label}//')" >> $GITHUB_ENV

    # Upload files to release
    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ env.upload_url }}
        asset_path: ./zip/  # Specify the path to the directory containing the generated zips
        asset_name: "*.zip"  # Name of the file, or use a wildcard for multiple files
        asset_content_type: application/zip
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}