name: Generate and Upload Zip Files

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Python environment
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install any necessary Python dependencies (e.g., if you use any non-standard libraries)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    # Run your Python script to generate the zip files
    - name: Run zip generation script
      run: |
        cd scripts
        python zipall.py

    # Upload files to release
    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./zip/  # Specify the path to the directory containing the generated zips
        asset_name: "*.zip"  # Name of the file, or use a wildcard for multiple files
        asset_content_type: application/zip

    # Create a release in GitHub
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}  # Use the tag that triggered the workflow
        release_name: "Release ${{ github.ref }}"
        draft: false
        prerelease: false
